Repository KostaMiniProject/MainProject-Front, pull requests merged in 2023-12, with the labels that each got.

#94 78 feat 교환 게시글 지도 플로팅 기능 2일차
  app/map/page.tsx
  components/Navbar.tsx
Labels: 기능개발, 창민

#98 23.12.18 지도 게시글 불러오기 진행중
  api/MapApi.tsx
  app/globals.css
  app/map/page.tsx
Labels: 기능개발, 창민

#107 Feat : 위치데이터를 함께 전송하는 로직 추가 및 판넬 디자인
  apis/MapApi.tsx
  app/map/page.tsx
  tailwind.config.ts
Labels: 기능개발, 창민

#114 전화번호 inputbox 타입 변경
  app/find/email/page.tsx
Labels: 코드수정, 윤진

#117 인증번호를 제외한 유효성 검사 리팩토링
  app/signup/page.tsx
Labels: 리팩토링

#118 116 feat 비밀번호 찾기 기능 개발
  apis/FindPasswordApi.tsx
  app/find/email/page.tsx
  app/find/email/success/page.tsx
  app/find/password/page.tsx
Labels: 기능개발, 코드수정, 윤진

#128 127 feat 로그인 비번 형식 변경 및 로고 이미지 변경
  app/login/page.tsx
  image/Logo.png
Labels: 코드수정, 윤진

#132 아이디 찾기 비밀번호 찾기 버튼 텍스트 수정
  app/find/email/success/page.tsx
  app/find/password/success/page.tsx
Labels: 리팩토링, 동건

#139 133 feat 남은 개발 마무리하기
  app/map/page.tsx
  app/postingexchange/page.tsx
Labels: 기능개발, 코드수정, 창민

#145 Feat : 내가 작성한 교환 게시글 보기 기능 구현 완료
  apis/ExchangePostApi.tsx
  app/myexchangepostlist/page.tsx
Labels: 기능개발, 창민

#147 126 feat 회원가입 이메일 인증 기능 구현
  apis/EmailCheckApi.tsx
  apis/EmailSendApi.tsx
  app/signup/page.tsx
Labels: 기능개발, 윤진

#148 133 feat 남은 개발 마무리하기
  apis/CommunityApi.tsx
  app/mycommunitypostlist/page.tsx
Labels: 기능개발, 창민

#152 차단 리스트 페이지 구현
  app/profile/block/page.tsx
Labels: 기능개발, 동건

#167 165 feat 본인이 차단한 사람들 리스트 제공 기능 추가
  apis/BlockedApi.tsx
  app/profile/block/page.tsx
Labels: 기능개발, 코드수정, 윤진

#168 회원 수정 페이지 및 프로필 페이지내 탈퇴하기 생성
  app/oauthsignup/page.tsx
  app/profile/editprofile/page.tsx
  app/profile/page.tsx
  app/signup/page.tsx
Labels: 기능개발, 동건

#171 무한 랜더링 오류 수정
  app/profile/block/page.tsx
Labels: 코드수정, 윤진

#174 찜 목록 페이지 구현
  app/additem/page.tsx
  app/oauthsignup/page.tsx
  app/profile/dib/page.tsx
  app/signup/page.tsx
  components/community/CommunityPostUnImage.tsx
Labels: 기능개발, 동건

#177 리뷰 리팩토링 및 페이지 간격 조절 작업
  app/additem/page.tsx
  app/bid/[id]/page.tsx
  app/biding/page.tsx
  app/exchange/[id]/page.tsx
  app/find/email/success/page.tsx
  app/find/password/success/page.tsx
  app/login/authcheck/page.tsx
  app/myexchangepostlist/page.tsx
  app/page.tsx
  app/postingexchange/selectitem/page.tsx
  app/profile/editprofile/page.tsx
  app/profile/exchangeHistory/page.tsx
  app/review/page.tsx
Labels: 리팩토링, 동건

#183 css 수정
  app/review/page.tsx
Labels: 코드수정, 동건

#185 페이지 간격 맞추기 작업
  app/biding/page.tsx
  app/chatting/[id]/page.tsx
  app/chatting/page.tsx
  app/community/[id]/page.tsx
  app/community/page.tsx
  app/exchange/[id]/page.tsx
  app/map/page.tsx
  app/postingexchange/selectitem/page.tsx
Labels: 코드수정, 동건

#207 비밀번호 코드 수정
  app/signup/page.tsx
Labels: 코드수정, 동건
